autenticacao/urls.py
from django.urls import include, path
from autenticacao.views import Login, Logout

app_name = "autenticacao"

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
]

dobrador/urls.py
from django.urls import include, path
from dobrador.views import DobradorList, DobradorEdit, DobradorDelete, DobradorNew

app_name = "dobradores"

urlpatterns = [
    path('listar', DobradorList.as_view(), name='listar'),
    path("novo/", DobradorNew.as_view(), name="novo"),
    path("<int:pk>/", DobradorEdit.as_view(), name="editar"),
    path("excluir/<int:pk>/", DobradorDelete.as_view(), name="excluir"),
]

projetoFinal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacao.urls', namespace='autenticacao')),
    path('dobradores/', include('dobrador.urls', namespace='dobradores')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

autenticacao/models.py
from django.db import models

# Create your models here.

dobrador/models.py
from django.db import models

# Create your models here.
class Dobrador(models.Model):

    nome = models.CharField(max_length=100)
    elemento = models.CharField('Elemento', max_length=100, choices=[('AR', 'AR'),('ÁGUA', 'ÁGUA'),('TERRA', 'TERRA'),('FOGO', 'FOGO')])
    descricao = models.TextField('Descrição Pessoal')
    profissao = models.CharField(max_length=100)
    idade = models.IntegerField('Idade')
    genero = models.CharField('Gênero', max_length=100, choices=[('MASCULINO', 'MASCULINO'),('FEMININO', 'FEMININO'),('NEUTRO', 'NEUTRO')])
    data_cadastro = models.DateTimeField('Primeiro acesso', auto_now_add=True)
    foto = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return '{0} - {1} ({2})'.format(self.nome, self.elemento, self.genero)

dobrador/forms.py
from django import forms
from dobrador.models import Dobrador

class FormularioDobrador(forms.ModelForm):

    class Meta:
        model = Dobrador
        exclude = []

autenticacao/views.py
from django.views.generic import View 
from django.shortcuts import render, redirect
from django.http import HttpResponse
# -*- coding: utf-8 -*-
from django.contrib.auth import authenticate, login
import logging
from dobrador.views import DobradorList
from django.contrib.auth import logout

logger = logging.getLogger(__name__)

class Login(View):

    def get(self, request):

        contexto = {
            'usuario':'',
            'senha':''
        }

        if request.user.is_authenticated:
            # Mudar para ir para a tela principal direto
            return redirect('dobradores/listar')

        return render(request, 'autenticacao/login.html', contexto)

    def post(self, request):

        # Armazena valores recebidos
        usuario = request.POST.get('usuario', None)
        senha = request.POST.get('senha', None)

        #Apresenta no log (terminal) os valores recebidos
        logger.info('Usuários: {usuario}'.format(usuario=usuario))
        logger.info('Senha: {senha}'.format(senha=senha))

        user = authenticate(request, username=usuario, password=senha)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('dobradores/listar')
            return render(request, 'autenticacao/login.html', {'mensagem':'Usuário inativo'})    
        return render(request, 'autenticacao/login.html', {'mensagem':'Usuário ou senha incorretos'}) 

class Logout(View):

    def get(self, request):
        logout(request)
        return render(request, 'autenticacao/login.html', {'mensagem':'Deslogado com sucesso!'}) 

dobrador/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView
from dobrador.models import Dobrador
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from dobrador.forms import FormularioDobrador
# Create your views here.

@method_decorator(login_required, name='dispatch')
class DobradorList(ListView):
    model = Dobrador
    context_object_name = "lista_dobradores"
    template_name = 'dobrador/listar.html'

@method_decorator(login_required, name='dispatch')
class DobradorNew(CreateView):
    
    model = Dobrador
    form_class = FormularioDobrador
    template_name = 'dobrador/novo.html'
    success_url = "/"    
    
@method_decorator(login_required, name='dispatch')
class DobradorEdit(UpdateView):
    
    model = Dobrador
    form_class = FormularioDobrador
    template_name = 'dobrador/editar.html'
    success_url = "/"

@method_decorator(login_required, name='dispatch')
class DobradorDelete(DeleteView):
    
    model = Dobrador
    template_name = 'dobrador/deletar.html'
    success_url = "/"

templates/autenticacao/login.html
{% load static %}
<!DOCTYPE html>


<html>

<head>
    <meta charset="utf-8">
    <title>Login sistema</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">
    <link href="//db.onlinewebfonts.com/c/d5e638ad62a611f703a8e0e951853da0?family=Herculanum" rel="stylesheet"
        type="text/css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

</html>

<body class="body">
    <h2 class="title-login">Dobradores de elementos</h2>
    <div class="card-login" style="width: 28rem; padding: 20px;">
        <h4 style="text-align: center;">Faça seu login</h4>
        <form class="form-div-login" action="/" method="POST">
            {% csrf_token %}
            <div style="display: flex; flex-direction: column;">
                <label>Usuário</label>
                <input class="form-control-login" type="text" name="usuario" id="usuario" value="{{ usuario }}">
            </div>

            <div style="display: flex; flex-direction: column;">
                <label>Senha</label>
                <input class="form-control-login" type="password" name="senha" id="senha" value="{{ senha }}">
            </div>


            <!-- <input type="submit" class="my-btn" data-toggle="button" aria-pressed="false"></input>  -->
            <input class="my-btn" type="submit" value="Login" />

        </form>
        {{mensagem}}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

templates/dobrador/base.html
{% load static %}
<!DOCTYPE html>


<html>

<head>
    <meta charset="utf-8">
    <title>Login sistema</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">
    <link href="//db.onlinewebfonts.com/c/d5e638ad62a611f703a8e0e951853da0?family=Herculanum" rel="stylesheet"
        type="text/css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

</html>

<body>
    <div class="header">
        <a href="/dobradores/listar"><p class="title-header">DOBRADORES</p></a>
        <a href="{% url 'dobradores:novo' %}"><p class="title-header">Novo</p></a>
        <a href="{% url 'autenticacao:logout' %}"><p class="title-header">Sair</p></a>
    </div>
    {% block content %}
    {% endblock content %}

</body>

templates/dobrador/deletar.html
{% extends "dobrador/base.html" %}
{% load static %}
{% load bootstrap %}
{% block content %}

<div class="main-form-div">
    <h2 >Excluir dobrador</h2>
    <div class="form">
        <form action="/dobradores/excluir/{{object.pk}}/" method="POST" style="width: 100%; gap: 10px;">
            {% csrf_token %}
            <p>Tem certeza que deseja excluir o "{{object}}"?</p>
            <input class="my-btn" type="submit" value="Confirmar" style="align-self: flex-end;" />
        </form>
    </div>
</div>
{% endblock content %}

templates/dobrador/editar.html
{% extends "dobrador/base.html" %}
{% load static %}
{% load bootstrap %}
{% block content %}

<div class="main-form-div">
    <h2 >Editar dobrador</h2>
    <div class="form">
        <form action="/dobradores/{{object.pk}}/" method="POST" style="width: 100%; gap: 10px;">
            {% csrf_token %}
            {{ form|bootstrap }}
            <input class="my-btn" type="submit" value="Confirmar" style="align-self: flex-end;" />
        </form>
    </div>
</div>
{% endblock content %}

templates/dobrador/listar.html
{% extends "dobrador/base.html" %}
{% load static %}

{% block content %}

<div class="grid-dobradores">
    {% for dobrador in lista_dobradores %}

    {% if dobrador.elemento == 'AR' %}
    <div class="card-dobradores-ar">
        {% elif dobrador.elemento == 'ÁGUA' %}
        <div class="card-dobradores-agua">
            {% elif dobrador.elemento == 'FOGO' %}
            <div class="card-dobradores-fogo">
                {% elif dobrador.elemento == 'TERRA' %}
                <div class="card-dobradores-terra">
                    {% endif %}
                    <div class="card-infos">

                        <div class="card-image">
                            {% if dobrador.foto %}
                            <img class="image-tag" src="{{ dobrador.foto.url }}" alt="image">
                            {% endif %}
                        </div>
                        <div style="display: flex; flex-direction: column; align-items: center;">
                            <p class="card-title">{{dobrador.nome}}</p>
                            <p class="card-subtitle">{{dobrador.profissao}}</p>
                            <div class="div-idade-genero">
                                <div class="div-inside-idade-genero">
                                    <p class="info-destaque">{{dobrador.idade}}</p>
                                    <p class="info-descricao">Idade</p>
                                </div>
                                <div class="div-inside-idade-genero">
                                    <p class="info-destaque">{{dobrador.genero}}</p>
                                    <p class="info-descricao">genero</p>
                                </div>

                            </div>
                            <div class="options">
                                <a class="options-link" href="/dobradores/{{ dobrador.pk }}">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil"
                                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                    </svg>
                                </a>
                                <a class="options-link" href="/dobradores/excluir/{{ dobrador.pk }}">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash"
                                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                        <path fill-rule="evenodd"
                                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                    </svg>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>
                {% endfor %}
            </div>

            {% endblock content %}

templates/dobrador/novo.html
{% extends "dobrador/base.html" %}
{% load static %}
{% load bootstrap %}
{% block content %}

<div class="main-form-div">
    <h2 >novo dobrador</h2>
    <div class="form">
        <form action="/dobradores/novo/" method="POST" style="width: 100%; gap: 10px;">
            {% csrf_token %}
            {{ form|bootstrap }}
            <input class="my-btn" type="submit" value="Criar" style="align-self: flex-end;" />
        </form>
    </div>
</div>
{% endblock content %}